name: MCP Checks

on:
  pull_request:
    paths:
      - mcp/**
      - .github/workflows/check_mcp.yml
  push:
    branches:
      - main
    paths:
      - mcp/**
      - .github/workflows/check_mcp.yml

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mcp

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --frozen
      - run: uv run pytest
